# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:02
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_productcategory_full_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
