# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:49
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
