# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20170721_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
